=== Reverssd18/M04---Lenguaje-de-Marcas/XML / DTD/generacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="primera_generacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="progenitor" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="persona">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Za-z\s]+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="yo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="persona">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[A-Za-z\s]+"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="segunda_generacion" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="persona">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Za-z\s]+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="tercera_generacion" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="persona" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[A-Za-z\s]+"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Reverssd18/M04---Lenguaje-de-Marcas/XML / DTD/generacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<primera_generacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generacion.xsd">
    <progenitor>
        <persona>
            <nombre>John Doe</nombre>
        </persona>
        <yo>
            <persona>
                <nombre>Victor</nombre>
            </persona>
        </yo>
    </progenitor>
    <segunda_generacion>
        <persona>
            <nombre>Jane Doe</nombre>
        </persona>
        <tercera_generacion>
            <persona>
                <nombre>Emily Doe</nombre> 
            </persona>
            <persona>
                <nombre>Michael Doe</nombre>
            </persona>
            <persona>
                <nombre>Sarah Doe</nombre>
            </persona>
            <persona>
                <nombre>David Doe</nombre>
            </persona>
            <persona>
                <nombre>James Doe</nombre>
            </persona>
        </tercera_generacion>
    </segunda_generacion>
</primera_generacion>
