=== Reverssd18/M04---Lenguaje-de-Marcas/XML / DTD/peli.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pelicula">
        <xs:complexType>
            <xs:sequence>
                <!-- persona -->
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z\s]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- pelicula -->
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genero">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z\s]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="titulo">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z0-9\s]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="director">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Za-z\s]+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="aÃ±o">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{4}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="actor_favorito" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Za-z\s]+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="edad" type="xs:integer"/>
                                        <xs:element name="sexo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="(Masculino|Femenino)"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Reverssd18/M04---Lenguaje-de-Marcas/XML / DTD/peli.xml
<?xml version="1.1" encoding="UTF-8" ?>
<!-- 
Nuestro nombre 
Nuestra edad
El guion de una pelicula que mas nos guste 
Nuestra pelicula favorita
El director de nuestra pelicula favorita
El año 
El actor que mas te gusta
La edad que tiene el actor
El genero del actor

-->
<pelicula xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="peli.xsd">
    <persona>
        <nombre>Victor Prieto</nombre>
        <edad>19</edad>
    </persona>
    <pelicula>
        <genero>Humor</genero>
        <titulo>Ocho apellidos vascos</titulo>
        <director>Emilio Martinez Lazaro</director>
        <año>2014</año>
        <actor_favorito>
            <nombre>Dani Rovira</nombre>
            <edad>44</edad>
            <sexo>Masculino</sexo>
        </actor_favorito>
    </pelicula>
</pelicula>
