=== Reverssd18/M04---Lenguaje-de-Marcas/XML / DTD/PR120.dtd
<!ELEMENT catalog (plant+)>
<!ELEMENT plant (common, botanical, zone, light, price, availability)>
<!ATTLIST plant id ID #REQUIRED>
<!ELEMENT common (#PCDATA)>
<!ELEMENT botanical (#PCDATA)>
<!ELEMENT zone (#PCDATA)>
<!ELEMENT light (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT availability (#PCDATA)>

=== Reverssd18/M04---Lenguaje-de-Marcas/XML / DTD/PR120.xml
<?xml version="1.1" encoding="UTF-8" ?>
<!DOCTYPE catalog SYSTEM "PR120.dtd">
<catalog>
<plant id="id_0">
    <common>Bloodroot</common>
    <botanical>Sanguinaria canadensis</botanical>
    <zone>4</zone>
    <light>Mostly Shady</light>
    <price>2.44</price>
    <availability>07162019</availability>
</plant>
<plant id="id_1">
    <common>Columbine</common>
    <botanical>Aquilegia canadensis</botanical>
    <zone>3</zone>
    <light>Mostly Shady</light>
    <price>9.37</price>
    <availability>07162019</availability>
</plant>
</catalog>
